name: "demo"

x-type: "hlfv1"

description: "demo network config"

version: "1.0"

client:
  organization: org1

  logging:
    level: info

  eventService:
    type: deliver
  cryptoconfig:
    path: ./artifacts/demo/crypto-config

  BCCSP:
    security:
     enabled: true
     default:
       provider: "SW"

     hashAlgorithm: "SHA2"

     softVerify: true
     ephemeral: false
     level: 256

  credentialStore:
      path: "./credentialStore/fabric-client-kv-org1"

      cryptoStore:
        path: "./cryptoStore/fabric-client-kv-org1"

      wallet: wallet-name

channels:

    
        
  channel2:
    orderers:
            
       - orderer0.demo.com
            
    peers:
            
              
      peer0.org1.demo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
              
            
    chaincodes:
            
        
    
        
  channel1:
    orderers:
            
       - orderer0.demo.com
            
    peers:
            
              
      peer0.org1.demo.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
              
            
    chaincodes:
            
      - map:1.0
            
        
    

organizations:

  org1:
    mspid: org1
    cryptoPath: peerOrganizations/org1.demo.com/users/{userName}@org1.demo.com/msp
    peers:
    
      - peer0.org1.demo.com
    
    
    certificateAuthorities:
      - ca.org1.demo.com
    
    adminPrivateKey:
      path: ./artifacts/demo/crypto-config/peerOrganizations/org1.demo.com/users/Admin@org1.demo.com/msp/keystore/92502773678e51364f5f5f43c80ee658c9ab9df8cedb8000ccdb9e05821e7b8b_sk
    signedCert:
      path: ./artifacts/demo/crypto-config/peerOrganizations/org1.demo.com/users/Admin@org1.demo.com/msp/signcerts/Admin@org1.demo.com-cert.pem

  OrdererOrg:
    mspID: OrdererOrg
    cryptoPath: ordererOrganizations/demo.com/users/{userName}@demo.com/msp

orderers:

  orderer0.demo.com:
    url: grpcs://192.168.137.50:7050
    grpcOptions:
      ssl-target-name-override: orderer0.demo.com
    tlsCACerts:
      path: ./artifacts/demo/crypto-config/ordererOrganizations/demo.com/orderers/orderer0.demo.com/tls/ca.crt



peers:

    
  peer0.org1.demo.com:
    url: grpcs://192.168.137.50:7051
    eventUrl: grpcs://192.168.137.50:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.demo.com
    tlsCACerts:
      path: ./artifacts/demo/crypto-config/peerOrganizations/org1.demo.com/peers/peer0.org1.demo.com/tls/ca.crt
    



certificateAuthorities:
  
  ca.org1.demo.com:
      
          
      
          
      
          
      
          
    url: https://ca.org1.demo.com:7054
    httpOptions:
      verify: false
    tlsCACerts:
      
      path: ./artifacts/demo/crypto-config/peerOrganizations/org1.demo.com/msp/cacerts/ca.org1.demo.com-cert.pem
      
    registrar:
      enrollId: admin
      enrollSecret: 3jlLo14q
    caName: ca.org1.demo.com
          
      
          
      
          
      
  



entityMatchers:
  peer:

    
    - pattern: peer0.org1.demo.com:(\d+)
      urlSubstitutionExp: 192.168.137.50:7051
      eventUrlSubstitutionExp:  192.168.137.50:7053
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.demo.com
      mappedHost: peer0.org1.demo.com
    

  orderer:

    - pattern: orderer0.demo.com:(\d+)
      urlSubstitutionExp: 192.168.137.50:7050
      sslTargetOverrideUrlSubstitutionExp: orderer0.demo.com
      mappedHost: orderer0.demo.com

  certificateAuthority:

    
         
    
         
    
         
    
         
    - pattern: ca.org1.demo.com:7054
      urlSubstitutionExp:  ca.org1.demo.com:7054
      mappedHost: ca.org1.demo.com
         
    
         
    
         
    


