OrdererOrgs:
  - Name: OrdererOrg
    Domain: demo.com
    CA:
      Country: CN
      Province: ShaanXi
      Locality: Xi'An
      Algorithm: ECDSA
    Specs:

      - CommonName: orderer0.demo.com


PeerOrgs:

    - Name: org1
      Domain: org1.demo.com
      EnableNodeOUs: true
      CA:
        Country: CN
        Province: ShaanXi
        Locality: Xi'An
        Algorithm: ECDSA
      Specs:
      
        - CommonName: peer0.org1.demo.com
      
      Users:
        Count: 1

